CREATE TABLE BOOKING(
 ID VARCHAR(36) DEFAULT RAWTOHEX(SYS_GUID ( )) PRIMARY KEY,
 TRX_ID VARCHAR(36),
 BOOKING_TYPE VARCHAR(20),
 BOOKING_TIME DATE DEFAULT SYSDATE NOT NULL,
 BOOKING_SUBJECT_ID INTEGER NOT NULL,
 STATUS VARCHAR(50) NOT NULL,
 LINK VARCHAR(100)
);

ALTER TABLE BOOKING ADD FOREIGN KEY (BOOKING_SUBJECT_ID) REFERENCES SUBJECTS (ID);
ALTER TABLE BOOKING ADD FOREIGN KEY (TRX_ID) REFERENCES PAYMENTS(TRX_ID);
ALTER TABLE BOOKING ADD CONSTRAINT TRX_UNIQUE UNIQUE (TRX_ID);