CREATE OR REPLACE TRIGGER INCREMENT_CLASSES_TRIGGER
    AFTER UPDATE OF LINK
    ON BOOKING
    FOR EACH ROW
DECLARE
    BKN_ID    VARCHAR(36);
    STUDENT_ID    VARCHAR(36);
    INSTRUCTOR_ID VARCHAR(36);
BEGIN
    BKN_ID := :NEW.ID;
    SELECT B.STUDENT_ID
    INTO STUDENT_ID
    FROM BOOKS B
    WHERE B.BOOKING_ID = BKN_ID;
    
    SELECT B.INSTRUCTOR_ID
    INTO INSTRUCTOR_ID
    FROM BOOKS B
    WHERE B.BOOKING_ID = BKN_ID;
		
    UPDATE STUDENTS SET CLASSES_ATTENDED = CLASSES_ATTENDED + 1 WHERE ID = STUDENT_ID;
    UPDATE INSTRUCTORS SET CLASSES_TAKEN = CLASSES_TAKEN + 1 WHERE ID = INSTRUCTOR_ID;
		DBMS_OUTPUT.PUT_LINE(STUDENT_ID);
		DBMS_OUTPUT.PUT_LINE(INSTRUCTOR_ID);
END;