CREATE OR REPLACE FUNCTION GET_BOOKING_STATUS(BOOKING_ID IN VARCHAR) RETURN VARCHAR IS
    BOOKING_STATUS VARCHAR(36);
BEGIN
    SELECT STATUS INTO BOOKING_STATUS FROM BOOKING WHERE ID = BOOKING_ID;
    RETURN BOOKING_STATUS;
END;