CREATE TABLE INSTRUCTORS (
	ID VARCHAR(36) DEFAULT RAWTOHEX(SYS_GUID ( )) PRIMARY KEY,
	ADDR_ID VARCHAR(36),
	NAME VARCHAR ( 50 ) NOT NULL,
	DATE_CREATED DATE DEFAULT SYSDATE,
	EMAIL VARCHAR ( 30 ) NOT NULL,
	USERNAME VARCHAR ( 30 ) UNIQUE NOT NULL,
	PASSWORD VARCHAR ( 82 ) NOT NULL,
	PHONE VARCHAR(30) NOT NULL,
	AGE INTEGER,
	GENDER VARCHAR ( 20 ),
	INSTITUTION VARCHAR ( 50 ),
	YEAR INTEGER,
	DEPARTMENT VARCHAR ( 10 ),
	RATING NUMBER(3,2),
	CLASSES_TAKEN INTEGER DEFAULT 0,
CHECK ( CLASSES_TAKEN >= 0 ) 
);
alter table INSTRUCTORS add foreign key (addr_id) references address(id);
