CREATE OR REPLACE TRIGGER LOG_BOOKS_DELETION
    BEFORE DELETE
    ON BOOKS
    FOR EACH ROW
DECLARE
    STUDENT_ID    VARCHAR(36);
    INSTRUCTOR_ID VARCHAR(36);
    BOOKING_ID    VARCHAR(36);
    DELETED_BY    VARCHAR(50);
BEGIN
    STUDENT_ID := :OLD.STUDENT_ID;
    INSTRUCTOR_ID := :OLD.INSTRUCTOR_ID;
    BOOKING_ID := :OLD.BOOKING_ID;
    DELETED_BY := GET_BOOKING_STATUS(BOOKING_ID);
    INSERT INTO BOOKS_DELETED (BOOKING_ID, STUDENT_ID, INSTRUCTOR_ID, DELETED_BY)
    VALUES (BOOKING_ID, STUDENT_ID, INSTRUCTOR_ID, DELETED_BY);
END;